### PR TITLE
htmlCanvas: Allow passing complex class names to addClass()

### PR DESCRIPTION
**Pull request by DamienCassou**
This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227)

### CODE REVIEW

**Review by BenjaminVanRyseghem — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227#-:-MuuHPqC9PN3Re00_QFi:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @DamienCassou)

___
*[src/htmlCanvas.js, line 514 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227#-MuuGnNgEShmCAI3vKR9:-MuuGnNgEShmCAI3vKRA:bls7lri) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/462458b7eb532fa34944f27844e51c26b5326eb6/src/htmlCanvas.js#L514)):*
> ```JavaScript
>  */
> TagBrushConstructor.prototype.removeClass = function(className) {
> 	this.asJQuery().removeClass(className);
> ```

nit: should we do the same here? so that we can pass the same argument to both?

like: 

```js
let classes = ["foo", {bar: baz()}];

if (toogleIsOn) {
    brush.addClass(classes);
} else {
    brush.removeClass(classes);
}

```
___
*[src/test/htmlCanvasTest.js, line 381 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227#-MuuHG6X4AHXXcNhXgH8:-MuuHG6X4AHXXcNhXgH9:b-p2ttqs) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/462458b7eb532fa34944f27844e51c26b5326eb6/src/test/htmlCanvasTest.js#L381)):*
> ```JavaScript
> 		withCanvas((html) => {
> 			let h1 = html.h1();
> 			function enabled() { false; }
> ```

nit: you can inline this one :smile:

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227)* status: all files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem)

___
*[src/htmlCanvas.js, line 514 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227#-MuuGnNgEShmCAI3vKR9:-MuuOz5P6tKNn5cb26Ys:b-7ql1td) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/462458b7eb532fa34944f27844e51c26b5326eb6/src/htmlCanvas.js#L514)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

nit: should we do the same here? so that we can pass the same argument to both?

like: 

```js
let classes = ["foo", {bar: baz()}];

if (toogleIsOn) {
    brush.addClass(classes);
} else {
    brush.removeClass(classes);
}

```
</blockquote></details>

fixed
___
*[src/test/htmlCanvasTest.js, line 381 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227#-MuuHG6X4AHXXcNhXgH8:-MuuPDP4Do0HOOofPhwj:b-7ql1td) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/462458b7eb532fa34944f27844e51c26b5326eb6/src/test/htmlCanvasTest.js#L381)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

nit: you can inline this one :smile:
</blockquote></details>

fixed

**Review by JohanBriglia — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227#-:-MuuQj-zEyeV6bQJyePV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem)

**Review by BenjaminVanRyseghem — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227)* status: all files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem)

___
*[src/htmlCanvas.js, line 514 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227#-MuuGnNgEShmCAI3vKR9:-MuuR7-1BDqXQDQqBN8e:bb6mt9b) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/462458b7eb532fa34944f27844e51c26b5326eb6/src/htmlCanvas.js#L514)):*
<details><summary><i>Previously, DamienCassou (Damien Cassou) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

:+1:

**Review by DamienCassou — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/227#-:-MuuSq0X8-Ggafqs6cjB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamienCassou)

**Pull request merged**
