### PR TITLE
37849678: Bump @foretagsplatsen/eslint-plugin in widgetjs

### PR DESCRIPTION
**Pull request by DamienCassou**
This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/499)

### CODE REVIEW

**Comment by BenjaminVanRyseghem** [comment]
https://3.basecamp.com/4201305/buckets/37849678/todos/7489012651

**Review by danglotb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/499#-:-O-_TIctBEdAURqGxv71:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @BenjaminVanRyseghem, @JohanBriglia, and @josquindebaz)

**Review by BenjaminVanRyseghem — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/499)* status: all files reviewed, 1 unresolved discussion (waiting on @DamienCassou, @JohanBriglia, and @josquindebaz)

___
*[`package.json` line 7 at r3](https://reviewable.io/reviews/foretagsplatsen/widgetjs/499#-O-_TTr40heLU0Fdn9Bf:-O-_TTr40heLU0Fdn9Bg:b-wsk03g) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/0065df5ff27bba535784dfcc75ae5724b910bb02/package.json#L7)):*
> ```JSON
>   "homepage": "http://github.com/foretagsplatsen/widgetjs",
>   "exports": {
>     ".": "./src/widgetjs.js"
> ```

nit: is this needed?

**Review by DamienCassou — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/499)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @BenjaminVanRyseghem, @danglotb, @dev-amin, @JohanBriglia, and @josquindebaz)

___
*[`package.json` line 46 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/499#-O-_BTKe-l70KkZQ59pG:-O-_BTKf3Fy-py2nKSA5:bjg8a0r) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/db45620d1ee405dc5e147e89ba6ab71161a284bf/package.json#L46)):*
> ```JSON
>   },
>   "devDependencies": {
>     "@foretagsplatsen/eslint-plugin": "^8.0.0-beta",
> ```

we should remove the "beta"
___
*[`package.json` line 47 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/499#-O-_BVk92szhi_eHQT9o:-O-_BVk92szhi_eHQT9p:bgeb7ti) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/db45620d1ee405dc5e147e89ba6ab71161a284bf/package.json#L47)):*
> ```JSON
>   "devDependencies": {
>     "@foretagsplatsen/eslint-plugin": "^8.0.0-beta",
>     "@stylistic/eslint-plugin-js": "2.1.0",
> ```

this should go away
___
*[`package.json` line 7 at r3](https://reviewable.io/reviews/foretagsplatsen/widgetjs/499#-O-_TTr40heLU0Fdn9Bf:-O-_jXnVBO7hwcAkB_JA:bennj9g) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/0065df5ff27bba535784dfcc75ae5724b910bb02/package.json#L7)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

nit: is this needed?
</blockquote></details>

no, thank you. Reverted

**Pull request merged**
