### PR TITLE
Svg support

### PR DESCRIPTION
**Pull request by NicolasPetton**
Add support for svg tags in htmlCanvas.

---
This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/101)

### CODE REVIEW

**Review by DamienCassou — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/101)* status: all files reviewed, 2 unresolved discussions (waiting on @NicolasPetton and @ValentinaVasile)

___
*[src/htmlCanvas.js, line 189 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/101#-MNwttSO2nZ4u4v5BODI:-MNwttSO2nZ4u4v5BODJ:brsf2ra) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/645eec49046bb87e7515dc9e571cc680b3bb0ef9/src/htmlCanvas.js#L189)):*
> ```JavaScript
>  */
> TagBrushConstructor.prototype.createElement = function(tagName, namespaceURI) {
> 	if (namespaceURI) {
> ```

why are you bypassing the cache here? (it's not as if I had any clue why this cache is useful so please don't ask).
___
*[src/test/htmlCanvasTest.js, line 413 at r2](https://reviewable.io/reviews/foretagsplatsen/widgetjs/101#-MNwuu4rDWp3pFigiP88:-MNwuu4rDWp3pFigiP89:b-2yag1o) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/b42d9f7a2633c85d69dfb42db7c0f65a5f83dfc0/src/test/htmlCanvasTest.js#L413)):*
> ```JavaScript
> 			withCanvas((html) => {
> 				["svg", "circle", "path", "polygon", "rect", "text"].forEach((tagName) => {
> 					console.log(html[tagName]);
> ```

you may want to remove this

**Review by NicolasPetton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/101)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @DamienCassou and @ValentinaVasile)

___
*[src/htmlCanvas.js, line 189 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/101#-MNwttSO2nZ4u4v5BODI:-MNxeEws3cespagwI8-o:bj7zfdy) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/645eec49046bb87e7515dc9e571cc680b3bb0ef9/src/htmlCanvas.js#L189)):*
<details><summary><i>Previously, DamienCassou (Damien Cassou) wrote…</i></summary><blockquote>

why are you bypassing the cache here? (it's not as if I had any clue why this cache is useful so please don't ask).
</blockquote></details>

The cache is there to avoid creating new DOM elements each time a make a new tag. It's an optimization technique that is common within frameworks that manipulate the DOM, as DOM element creation can be a bit expensive.

I don't want to use the cache here though because I don't know the consequences it would have on SVG elements, I don't know enough about them to feel confident about caching. Also I don't know if a clone is faster than creating a new element.

**Review by DamienCassou — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/101#-:-MNxfFM62WT-dOG9aFti:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ValentinaVasile)

**Review by NicolasPetton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/101)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ValentinaVasile)

___
*[src/htmlCanvas.js, line 189 at r1](https://reviewable.io/reviews/foretagsplatsen/widgetjs/101#-MNwttSO2nZ4u4v5BODI:-MNxfFWx27bwbfqS35H9:b-jwfwky) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/645eec49046bb87e7515dc9e571cc680b3bb0ef9/src/htmlCanvas.js#L189)):*
<details><summary><i>Previously, NicolasPetton (Nicolas Petton) wrote…</i></summary><blockquote>

The cache is there to avoid creating new DOM elements each time a make a new tag. It's an optimization technique that is common within frameworks that manipulate the DOM, as DOM element creation can be a bit expensive.

I don't want to use the cache here though because I don't know the consequences it would have on SVG elements, I don't know enough about them to feel confident about caching. Also I don't know if a clone is faster than creating a new element.
</blockquote></details>

Another reason is that there might be tag name conflicts between SVG and HTML elements, so I did not want to use the same cache. If speed becomes a problem one (it probably never will), we can then think about having one cache per namespace URI so that SVG elements are cached separately from HTML elements.

**Pull request merged**
