### PR TITLE
Make eslint happy

### PR DESCRIPTION
**Pull request by DamienCassou**
I used the same rules as in Klassified.

### CODE REVIEW

**Comment by DamienCassou** [comment]
This hopefully fixes #39

**Comment by NicolasPetton** [comment]
:ok_hand: :rocket:

**Comment by DamienCassou** [comment]
@NicolasPetton Does your comment mean I can merge?

**Comment by NicolasPetton** [comment]
Damien Cassou <notifications@github.com> writes:

> @NicolasPetton Does your comment mean I can merge?

If eslint's happy, I'm happy!

**Pull request merged**
