### PR TITLE
Update yarn.lock

### PR DESCRIPTION
**Pull request by DamienCassou**
This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/129)

### CODE REVIEW

**Review by BenjaminVanRyseghem — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/129)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @DamienCassou)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/129#-Mhs4X9w-1zv9es32OU8:-Mhs4X9w-1zv9es32OU9:b8d8dy1) (no related file):*
this is quite strange? did we forget to commit it when updating a dependency or something? It's usually not a file that we manually update alone, or?

---

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/129)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/129#-Mhs4X9w-1zv9es32OU8:-Mhs7zN_9yF3FlATZjV1:b-lk29a2) (no related file):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

this is quite strange? did we forget to commit it when updating a dependency or something? It's usually not a file that we manually update alone, or?
</blockquote></details>

no, this is normal. You do that when you want to update indirect dependencies to their latest versions compatible with what you have requested in package.json.

Here is an example PR automatically made by dependabot: https://github.com/foretagsplatsen/widgetjs/pull/100. It only updates the lock file to fix a security issue with an indirect dependency.

---

**Review by BenjaminVanRyseghem — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamienCassou)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/129#-Mhs4X9w-1zv9es32OU8:-Mhs8dofEcT-7Q9m1sLj:bu2ayiw) (no related file):*
<details><summary><i>Previously, DamienCassou (Damien Cassou) wrote…</i></summary><blockquote>

no, this is normal. You do that when you want to update indirect dependencies to their latest versions compatible with what you have requested in package.json.

Here is an example PR automatically made by dependabot: https://github.com/foretagsplatsen/widgetjs/pull/100. It only updates the lock file to fix a security issue with an indirect dependency.
</blockquote></details>

ok :) Didn't know that :smile: Then maybe the commit message could tell which dependency you are updating?

---

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/129)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/129#-Mhs4X9w-1zv9es32OU8:-Mhs9Kcr8l1zU0WuMnsv:b-skpx6a) (no related file):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

ok :) Didn't know that :smile: Then maybe the commit message could tell which dependency you are updating?
</blockquote></details>

all of them :-). I just deleted the lock file and ask yarn to generate it from scratch.

---

**Pull request merged**
