### PR TITLE
6.0.0 release

### PR DESCRIPTION
**Pull request by DamienCassou**
This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112)

### CODE REVIEW

**Review by BenjaminVanRyseghem — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohanBriglia)

**Review by JohanBriglia — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112#-:-MhSmLTa4dnogpYapopW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamienCassou)

**Review by BenjaminVanRyseghem — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112)* status: all files reviewed, 2 unresolved discussions (waiting on @DamienCassou)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112#-MhT-GJ61s-5B5qKWFP6:-MhT-GJ61s-5B5qKWFP7:barezmx) (no related file):*
I have the feeling you are adding a lot to this "release". Shouldn't you do the CodeOwner thingy and dependabot, then do a release?

---
___
*[.github/dependabot.yml, line 12 at r4](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112#-MhT-b1m3cYPVRb8ljMu:-MhT-b1m3cYPVRb8ljMv:b-u6wg2e) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/0cd7e095c3dfaa2221f0276df558e9a2f9fec03f/.github/dependabot.yml#L12)):*
> ```
>  "15549487: "
> ```

what does that mean?

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112)* status: all files reviewed, 2 unresolved discussions (waiting on @BenjaminVanRyseghem)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112#-MhT-GJ61s-5B5qKWFP6:-MhTFdSnBPhiJMqTD5g_:bifw4rq) (no related file):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

I have the feeling you are adding a lot to this "release". Shouldn't you do the CodeOwner thingy and dependabot, then do a release?
</blockquote></details>

I created a dedicated PR

---
___
*[.github/dependabot.yml, line 12 at r4](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112#-MhT-b1m3cYPVRb8ljMu:-MhTFfS_AdnDj6a157S6:br3ego1) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/0cd7e095c3dfaa2221f0276df558e9a2f9fec03f/.github/dependabot.yml#L12)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

> ```
>  "15549487: "
> ```

what does that mean?
</blockquote></details>

I added a comment in the dedicated PR

**Review by BenjaminVanRyseghem — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/112#-:-MhTThCX7tlUU_vxD24B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @DamienCassou)

**Pull request merged**
