### PR TITLE
32129139: Improve some unit tests

### PR DESCRIPTION
**Pull request by DamienCassou**
https://3.basecamp.com/4201305/buckets/32129139/todos/7278579439

This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/487)

### CODE REVIEW

**Review by ValentinaVasile — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/487)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @BenjaminVanRyseghem, @DamienCassou, @danglotb, @JohanBriglia, and @josquindebaz)

___
*[`src/test/router/routerTest.js` line 187 at r4](https://reviewable.io/reviews/foretagsplatsen/widgetjs/487#-Nv5tW762ryOXeATA0O7:-Nv5tW762ryOXeATA0O8:b-auqg6b) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/1239e04f0d958772352b3a7bca44ea290871cbbc/src/test/router/routerTest.js#L187)):*
> ```JavaScript
> 		// Assert that callback was executed
> 		expect(spy).toHaveBeenCalledWith(jasmine.anything());
> 	});
> ```

Why is this assertion better than the previous one?

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/487)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @BenjaminVanRyseghem, @danglotb, @JohanBriglia, @josquindebaz, and @ValentinaVasile)

___
*[`src/test/router/routerTest.js` line 187 at r4](https://reviewable.io/reviews/foretagsplatsen/widgetjs/487#-Nv5tW762ryOXeATA0O7:-Nv5u5NC2u273dHD3oOh:b-hlm11u) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/1239e04f0d958772352b3a7bca44ea290871cbbc/src/test/router/routerTest.js#L187)):*
<details><summary><i>Previously, ValentinaVasile (Valentina Vasile) wrote…</i></summary><blockquote>

Why is this assertion better than the previous one?
</blockquote></details>

it checks the function was called with one and only one argument. Not much better I agree but some eslint rules forbid the use of `toHaveBeenCalled()`.

**Review by ValentinaVasile — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/487#-:-Nv5vNWiB2WX52nBclF3:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @BenjaminVanRyseghem, @DamienCassou, @danglotb, @JohanBriglia, and @josquindebaz)

___
*[`src/test/router/routerTest.js` line 187 at r4](https://reviewable.io/reviews/foretagsplatsen/widgetjs/487#-Nv5tW762ryOXeATA0O7:-Nv5vJZb4ZI3SCcLsVn5:b-k3u6ju) ([raw file](https://github.com/foretagsplatsen/widgetjs/blob/1239e04f0d958772352b3a7bca44ea290871cbbc/src/test/router/routerTest.js#L187)):*
<details><summary><i>Previously, DamienCassou (Damien Cassou) wrote…</i></summary><blockquote>

it checks the function was called with one and only one argument. Not much better I agree but some eslint rules forbid the use of `toHaveBeenCalled()`.
</blockquote></details>

thanks for the answer

**Review by josquindebaz — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/widgetjs/487)* status: all files reviewed, 1 unresolved discussion (waiting on @BenjaminVanRyseghem, @DamienCassou, @danglotb, and @JohanBriglia)

**Pull request merged**
